version: '3.8'

services:
  # 1. The River (Ephemeral)
  redis:
    image: redis:alpine
    container_name: kairos_redis
    ports:
      - "6379:6379"
    command: redis-server --notify-keyspace-events Ex
    networks:
      - kairos_net

  # 2. The Rock (Permanent) - NEW
  postgres:
    image: postgres:15-alpine
    container_name: kairos_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kairos_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kairos_net

networks:
  kairos_net:
    driver: bridge

volumes:
  postgres_data: